{% set name = "elphmod" %}
{% set version = "0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5afc215a280d230ebbd1e9aad33777a68a2165275b97bff9414c3594985501ff

build:
  entry_points:
    - elphmodenv = elphmod.MPI:elphmodenv
    - kpoints = elphmod.bravais:kpoints
    - minimum = elphmod.misc:minimum
    - ph2epw = elphmod.elph:ph2epw
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - flit-core >=3.4
    - pip
  run:
    - python >=3.5
    - numpy
    - scipy

test:
  imports:
    - elphmod
  commands:
    - pip check
    - elphmodenv
  requires:
    - pip

about:
  home: https://github.com/janberges/elphmod
  summary: Python modules for electron-phonon models
  description: |
    elphmod is a collection of Python modules to handle coupled tight-binding and
    mass-spring models derived from first principles. It provides interfaces with
    popular simulation software such as Quantum ESPRESSO, Wannier90, EPW, RESPACK,
    and i-PI. It helps calculate dispersions, spectra, and response functions and
    can be used to build and study distorted structures on supercells.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://janberges.github.io/elphmod
  dev_url: https://github.com/janberges/elphmod

extra:
  recipe-maintainers:
    - janberges
